#!/bin/bash
SERVER_PROPERTIES=server.properties
CRAFTBUKKIT_SERVER_JAR=spigot.jar

set -x 

cd $OPENSHIFT_DATA_DIR

if [ ! -e "$CRAFTBUKKIT_SERVER_JAR" ]; then
	wget "http://indungo.tk/downloads/1.8.3/spigot.jar" -O $CRAFTBUKKIT_SERVER_JAR
fi

